import type { SubcommandDefinition } from '@src/system/command-definition';

export const bottomupGenerateDefinition = (
  prefix: string,
  alias: string,
): SubcommandDefinition => ({
  name: 'bottomup.generate',
  summary: 'Generate source-grounded .BOTTOMUP.json knowledge.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'path',
      summary: 'Directory to generate, relative to workspace root.',
      flag: '--path',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'root',
      summary: 'Logical bottom-up root relative to workspace root.',
      flag: '--root',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'recursive',
      summary: 'Generate the requested directory and all descendants.',
      flag: '--recursive',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'enrich',
      summary: 'Also create contextual knowledge for generated directories.',
      flag: '--enrich',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'context',
      summary: 'Big-picture context used with --enrich.',
      flag: '--context',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
      webInput: 'textarea',
    },
    {
      name: 'prompt',
      summary: 'Optional generation instructions.',
      flag: '--prompt',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
      webInput: 'textarea',
    },
    {
      name: 'model',
      summary: 'Override the model used for generation.',
      flag: '--model',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'ignore',
      summary: 'Comma-separated extra ignore patterns.',
      flag: '--ignore',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'includeHidden',
      summary: 'Include hidden source files and directories.',
      flag: '--include-hidden',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'noGitignore',
      summary: 'Do not respect .gitignore rules.',
      flag: '--no-gitignore',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'draft',
      summary: 'Create an in-memory web review draft instead of writing.',
      flag: '--draft',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'plan',
      summary: 'Show resolved scope and expected work without AI or writes.',
      flag: '--plan',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
  ],
  examples: [
    `${prefix}${alias} bottomup.generate --path plugins/todo/commands/create`,
    `${prefix}${alias} bottomup.generate --path plugins/todo --root plugins/todo --recursive`,
    `${prefix}${alias} bottomup.generate --path plugins/todo/commands/create --enrich --context "Todo architecture"`,
    `${prefix}${alias} bottomup.generate --path plugins/todo --plan`,
  ],
  webExecutionMode: 'requires_input',
});

export const bottomupGenerateReviseDefinition = (
  _prefix: string,
  _alias: string,
): SubcommandDefinition => ({
  name: 'bottomup.generate.revise',
  summary: 'Revise an in-memory bottom-up generation draft.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory draft state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'prompt',
      summary: 'Revision instructions.',
      flag: '--prompt',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
      webInput: 'textarea',
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});

export const bottomupGenerateAcceptDefinition = (
  _prefix: string,
  _alias: string,
): SubcommandDefinition => ({
  name: 'bottomup.generate.accept',
  summary: 'Accept an in-memory bottom-up generation draft.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory draft state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});
