import type { SubcommandDefinition } from '@src/system/command-definition';

export const bottomupSummaryDefinition = (
  prefix: string,
  alias: string,
): SubcommandDefinition => ({
  name: 'bottomup.summary',
  summary: 'Read current knowledge from .BOTTOMUP.json indexes.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'path',
      summary: 'Directory or file to read, relative to workspace root.',
      flag: '--path',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'root',
      summary: 'Logical bottom-up root relative to workspace root.',
      flag: '--root',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'format',
      summary: 'Render as Markdown or JSON.',
      flag: '--format',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: ['markdown', 'json'],
    },
    {
      name: 'parentDepth',
      summary: 'Number of stored parent levels to include.',
      flag: '--parent-depth',
      shortFlag: null,
      kind: 'integer',
      required: false,
      choices: null,
    },
    {
      name: 'childDepth',
      summary: 'Number of stored child levels to include.',
      flag: '--child-depth',
      shortFlag: null,
      kind: 'integer',
      required: false,
      choices: null,
    },
    {
      name: 'location',
      summary: 'Optional workspace-relative path for an exported projection.',
      flag: '--location',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'draft',
      summary: 'Open a web preview with an optional export form.',
      flag: '--draft',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
  ],
  examples: [
    `${prefix}${alias} bottomup.summary --path plugins/file`,
    `${prefix}${alias} bottomup.summary --path plugins/file/commands --parent-depth 2`,
    `${prefix}${alias} bottomup.summary --path plugins/file --format json`,
    `${prefix}${alias} bottomup.summary --path plugins/file --location plugins/file/BOTTOMUP_SUMMARY.md`,
  ],
  webExecutionMode: 'requires_input',
});

export const bottomupSummarySaveDefinition = (): SubcommandDefinition => ({
  name: 'bottomup.summary.save',
  summary: 'Save a reviewed bottom-up summary projection.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory summary preview state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'location',
      summary: 'Workspace-relative export location.',
      flag: '--location',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});
