import type { SubcommandDefinition } from '@src/system/command-definition';

export const bottomupSummarizeDefinition = (
  prefix: string,
  alias: string,
): SubcommandDefinition => ({
  name: 'bottomup.summarize',
  summary: 'Build compact hierarchical summaries in .BOTTOMUP.json files.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'path',
      summary: 'Directory subtree to summarize, relative to workspace root.',
      flag: '--path',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'root',
      summary: 'Logical bottom-up root relative to workspace root.',
      flag: '--root',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'prompt',
      summary: 'Optional summarization instructions.',
      flag: '--prompt',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
      webInput: 'textarea',
    },
    {
      name: 'noPartial',
      summary: 'Reject missing or stale generated coverage.',
      flag: '--no-partial',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'model',
      summary: 'Override the model used for summarization.',
      flag: '--model',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'ignore',
      summary: 'Comma-separated extra ignore patterns.',
      flag: '--ignore',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'includeHidden',
      summary: 'Include hidden source files and directories.',
      flag: '--include-hidden',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'noGitignore',
      summary: 'Do not respect .gitignore rules.',
      flag: '--no-gitignore',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'draft',
      summary: 'Create an in-memory web review draft instead of writing.',
      flag: '--draft',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'plan',
      summary: 'Show coverage and expected work without AI or writes.',
      flag: '--plan',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
  ],
  examples: [
    `${prefix}${alias} bottomup.summarize --path plugins/todo`,
    `${prefix}${alias} bottomup.summarize --path plugins/todo --no-partial --draft`,
    `${prefix}${alias} bottomup.summarize --path plugins/todo --plan`,
  ],
  webExecutionMode: 'requires_input',
});

export const bottomupSummarizeReviseDefinition = (): SubcommandDefinition => ({
  name: 'bottomup.summarize.revise',
  summary: 'Revise an in-memory bottom-up summarize draft.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory summarize draft state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'prompt',
      summary: 'Revision instructions.',
      flag: '--prompt',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
      webInput: 'textarea',
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});

export const bottomupSummarizeAcceptDefinition = (): SubcommandDefinition => ({
  name: 'bottomup.summarize.accept',
  summary: 'Accept an in-memory bottom-up summarize draft.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory summarize draft state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});
