import type { SubcommandDefinition } from '@src/system/command-definition';

export const bottomupEnrichDefinition = (
  prefix: string,
  alias: string,
): SubcommandDefinition => ({
  name: 'bottomup.enrich',
  summary: 'Enrich .BOTTOMUP.json knowledge from stored summaries and context.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'path',
      summary: 'Directory subtree to enrich, relative to workspace root.',
      flag: '--path',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'root',
      summary: 'Logical bottom-up root relative to workspace root.',
      flag: '--root',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'context',
      summary: 'Optional replacement big-picture context.',
      flag: '--context',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
      webInput: 'textarea',
    },
    {
      name: 'prompt',
      summary: 'Optional enrichment instructions.',
      flag: '--prompt',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
      webInput: 'textarea',
    },
    {
      name: 'allowPartial',
      summary: 'Skip missing, stale, or context-blocked directories.',
      flag: '--allow-partial',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'force',
      summary: 'Regenerate enrichment even when input hashes match.',
      flag: '--force',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'model',
      summary: 'Override the model used for enrichment.',
      flag: '--model',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'ignore',
      summary: 'Comma-separated extra ignore patterns.',
      flag: '--ignore',
      shortFlag: null,
      kind: 'string',
      required: false,
      choices: null,
    },
    {
      name: 'includeHidden',
      summary: 'Include hidden source files and directories.',
      flag: '--include-hidden',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'noGitignore',
      summary: 'Do not respect .gitignore rules.',
      flag: '--no-gitignore',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'draft',
      summary: 'Create an in-memory web review draft instead of writing.',
      flag: '--draft',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
    {
      name: 'plan',
      summary: 'Show coverage and expected work without AI or writes.',
      flag: '--plan',
      shortFlag: null,
      kind: 'boolean',
      required: false,
      choices: null,
    },
  ],
  examples: [
    `${prefix}${alias} bottomup.enrich --path plugins/todo`,
    `${prefix}${alias} bottomup.enrich --path plugins/todo --context "Todo architecture"`,
    `${prefix}${alias} bottomup.enrich --path plugins/todo --allow-partial`,
    `${prefix}${alias} bottomup.enrich --path plugins/todo --plan`,
  ],
  webExecutionMode: 'requires_input',
});

export const bottomupEnrichReviseDefinition = (): SubcommandDefinition => ({
  name: 'bottomup.enrich.revise',
  summary: 'Revise an in-memory bottom-up enrichment draft.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory enrichment draft state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
    {
      name: 'prompt',
      summary: 'Revision instructions.',
      flag: '--prompt',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
      webInput: 'textarea',
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});

export const bottomupEnrichAcceptDefinition = (): SubcommandDefinition => ({
  name: 'bottomup.enrich.accept',
  summary: 'Accept an in-memory bottom-up enrichment draft.',
  aliases: [],
  arguments: [],
  options: [
    {
      name: 'state',
      summary: 'Encoded in-memory enrichment draft state.',
      flag: '--state',
      shortFlag: null,
      kind: 'string',
      required: true,
      choices: null,
    },
  ],
  examples: [],
  textHidden: true,
  webExecutionMode: 'requires_input',
});
